version: '24.0.5'
services:
  api:
    build: ./api
    container_name: api_c
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
      - /app/node_modules
  my_blog:
    build: ./myblog
    container_name: my_blog_c
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
